# Makefile for assignment 2 Java - Parallel Programming
# Author: Ian Wilkes

JAVAC= javac

all: CoinFlipper SealedDES

SealedDES:
	$(JAVAC) SealedDES.java

CoinFlipper:
	$(JAVAC) CoinFlipper.java

clean:
	rm -rf *.class
